# Generated by Django 5.2 on 2025-04-23 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='is_active',
        ),
        migrations.AddField(
            model_name='device',
            name='authorized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='distance',
            field=models.FloatField(help_text='Distancia en km', null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='duration',
            field=models.IntegerField(help_text='Duración en segundos'),
        ),
    ]
